version: '3.9'

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress-app

    ports:
      - "8080:80"

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - frontend-net
      - backend-net

    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql-db

    restart: always

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      - backend-net

    volumes:
      - mysql_data:/var/lib/mysql

volumes:

  mysql_data:

  wordpress_data:

networks:

  frontend-net:

  backend-net: